name: Deploy client to Vercel

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (client)
        working-directory: ./client
        run: |
          npm ci

      - name: Build (client)
        working-directory: ./client
        run: |
          npm run build --if-present

      - name: Install Vercel CLI
        run: npm i -g vercel@28

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          vercel --token "$VERCEL_TOKEN" --prod --confirm --cwd ./client --org=$VERCEL_ORG_ID --project=$VERCEL_PROJECT_ID
