name: Deploy client to Vercel

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (repo root)
        run: |
          npm ci

      - name: Build (root) -> produces dist/public
        run: |
          npm run build

      - name: Install Vercel CLI
        run: npm i -g vercel@28

      - name: Deploy built static folder to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          # Deploy the generated static output (dist/public) so the built JS/CSS are served correctly
          vercel --token "$VERCEL_TOKEN" --prod --confirm ./dist/public --org=$VERCEL_ORG_ID --project=$VERCEL_PROJECT_ID
